import { Poppins } from "next/font/google";
import { Manrope } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Use correct weights
  variable: "--font-poppins",
});

const manrope = Manrope({subsets: ["latin"]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
